[package]
name = "rudle"
version = "0.1.0"
edition = "2021"

[dependencies]
better-panic = "0.3.0"
clap = { version = "4.5.21", features = ["derive"] }
clearscreen = "3.0.0"
inline_colorization = "0.1.6"
rand = "0.8.5"
serde_json = "1.0.133"
